-- Role: "MCTGAdmin"
-- DROP ROLE "MCTGAdmin";

CREATE ROLE "MCTGAdmin" WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:Ff1Z0wSrAtOPAAx9VUqYZw==$KHYeu05s1IIXJJ2BTMZO9bAWdbWa8wHEfdhXJlJAUe4=:6GV6jxsOrxVdYXAdUoP3pgeFEWrbxs7uSAgLiFGRKRw=';


CREATE DATABASE "MCTG"
    WITH 
    OWNER = "MCTGAdmin"
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE "MCTG" TO "MCTGAdmin";

GRANT TEMPORARY, CONNECT ON DATABASE "MCTG" TO PUBLIC;


